/* ================= ACTIONS ================= */
function login(){DB.user=($('#em').value.split('@')[0]||'Investigator');localStorageSet('user',DB.user);location.hash='#/dashboard'}
function saveCfg(){CFG.API_BASE=$('#api').value;CFG.USE_MOCK=$('#mode').value=='1';localStorageSet('api',CFG.API_BASE);toast('Settings saved')}
function fillDemo(){a_u.value='official_sbi_help';a_f.value=95;a_g.value=1800;a_po.value=3;a_ag.value=9;a_b.value='Official support page. DM for loan help';a_c.value='Click link to verify your account now! Guaranteed refund via WhatsApp.'}
async function runAnalyze(){if(!a_u.value.trim())return toast('Enter a username');go.disabled=true;go.textContent='Analyzing…';
 const r=await API.analyze({username:a_u.value.trim(),platform:a_pl.value,followers:+a_f.value,following:+a_g.value,posts:+a_po.value,age_days:+a_ag.value,bio:a_b.value,captions:a_c.value});
 go.disabled=false;go.textContent='Run analysis';window._last=r;
 $('#res').innerHTML=`<h3>Result for @${esc(r.username)}</h3><div class="row sp"><div>${gauge(r.risk,'unified risk')}</div><div style="flex:1;min-width:180px"><p>${risk(r.risk)}</p>${meter('ML fake-probability',r.ml)}${meter('LLM content risk',r.llm)}</div></div><h3 style="margin-top:16px">Feature contributions</h3>${r.features.map(f=>meter(f[0],f[1])).join('')}<h3>LLM verdict</h3><pre>${esc(JSON.stringify({verdict:r.verdict,flags:r.flags,rationale:r.rationale},null,2))}</pre><div class=row><button class=btn onclick="saveLast()">Add to queue &amp; open</button></div>`}
function saveLast(){const p=window._last;p.id=DB.profiles.length+1;DB.profiles.unshift(p);location.hash='#/profile/'+p.id}
function filt(){const q=$('#q').value.toLowerCase(),r=$('#fr').value,pl=$('#fp').value,s=$('#fs').value;
 $('#tbl').innerHTML=profTable(DB.profiles.filter(p=>p.username.toLowerCase().includes(q)&&(!r||cls(p.risk)==r)&&(!pl||p.platform==pl)&&(!s||p.status==s)))}
function exportCSV(){const c='username,platform,followers,following,age_days,risk\n'+DB.profiles.map(p=>[p.username,p.platform,p.followers,p.following,p.age_days,p.risk.toFixed(2)].join(',')).join('\n');dl('profiles.csv',c,'text/csv')}
function dl(n,c,t){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([c],{type:t}));a.download=n;a.click()}
function loadFile(i){const f=i.files[0];if(!f)return;const r=new FileReader();r.onload=()=>$('#bl').value=r.result.split(/[\r\n,]+/).filter(Boolean).join('\n');r.readAsText(f)}
async function runBatch(){const n=$('#bl').value.split('\n').map(s=>s.trim()).filter(Boolean);if(!n.length)return toast('Add at least one username');
 $('#bp').innerHTML='<p class=mut>Screening '+n.length+' accounts…</p><div class=bar><i style="width:100%;background:var(--pri)"></i></div>';
 const res=await API.batch(n);window._batch=res;$('#bp').innerHTML='';
 $('#br').innerHTML=`<div class=card><div class="row sp"><h3>${res.length} accounts screened · ${res.filter(p=>p.risk>=.7).length} high risk</h3><button class=btn onclick="DB.profiles.unshift(...window._batch);toast('Added to queue');location.hash='#/profiles'">Add all to queue</button></div>${profTable(res,false)}</div>`}
function detail(id){const p=DB.profiles.find(x=>x.id==id);if(!p)return shell('profiles','Not found','<div class=card>Profile not found.</div>');
 return shell('profiles','@'+esc(p.username),`<div class="grid g2"><div class=card><div class="row sp"><div>${gauge(p.risk,'unified risk')}</div><div style="flex:1;min-width:200px"><p>${risk(p.risk)} <span class="pill n">${p.status}</span></p><p class=mut>${p.platform} · flagged ${p.date}</p>${meter('ML score',p.ml)}${meter('LLM score',p.llm)}</div></div><div class=row style="margin-top:14px"><button class=btn onclick="setStatus(${p.id},'Escalated')">Escalate</button><button class="btn ghost" onclick="setStatus(${p.id},'Dismissed')">Dismiss</button><button class="btn ghost" onclick="setStatus(${p.id},'Open')">Reopen</button><button class="btn red" onclick="location.hash='#/report/'+makeReport(DB.profiles.find(x=>x.id==${p.id})).id">Generate report</button></div></div>
 <div class=card><h3>Profile facts</h3><table>${[['Followers',p.followers],['Following',p.following],['Posts',p.posts],['Account age',p.age_days+' days'],['Bio',p.bio||'— empty —']].map(r=>`<tr><td class=mut>${r[0]}<td>${esc(r[1])}</tr>`).join('')}</table></div></div>
 <div class="grid g2"><div class=card><h3>Feature contributions</h3>${p.features.map(f=>meter(f[0],f[1])).join('')}</div><div class=card><h3>LLM content analysis</h3><p><b>${p.verdict}</b></p><p>${(p.flags.map(f=>`<span class=tag>${esc(f)}</span>`).join(''))||'<span class=mut>No flags</span>'}</p><p class=mut>${p.rationale}</p></div></div>`)}
function setStatus(id,s){DB.profiles.find(x=>x.id==id).status=s;toast('Status: '+s);route()}
function reportView(id){const r=DB.reports.find(x=>x.id==id);if(!r)return shell('reports','Report','<div class=card>Report not found.</div>');const p=r.profile;
 return shell('reports','Report '+r.id,`<div class="row noprint" style="margin-bottom:14px"><button class=btn onclick="window.print()">🖨 Print / Save as PDF</button><button class="btn ghost" onclick="dl('${r.id}.json',JSON.stringify(DB.reports.find(x=>x.id=='${r.id}'),null,2),'application/json')">⬇ JSON</button></div>
 <div class=card><h2>Investigation Report – ${r.id}</h2><p class=mut>Generated ${r.created} · FakeProfile Shield · Team G-9</p><h3>Subject</h3><p>@${esc(p.username)} on ${p.platform}</p><h3>Assessment</h3><p>${risk(p.risk)} — ML ${pct(p.ml)}, LLM ${pct(p.llm)}</p><h3>Behavioural evidence</h3><ul>${p.features.map(f=>`<li>${f[0]}: ${pct(f[1])} contribution`).join('')}</ul><h3>Content findings</h3><p><b>${p.verdict}.</b> ${p.rationale}</p><p>${p.flags.map(f=>`<span class=tag>${esc(f)}</span>`).join('')}</p><h3>Recommended action</h3><p>${p.risk>=.7?'Escalate for takedown request and preserve evidence.':p.risk>=.4?'Manual review recommended.':'No action required.'}</p></div>`)}
