/* ================= COMPONENTS ================= */
const gauge=(v,l)=>`<div class=gauge style="background:conic-gradient(${col(v)} ${v*360}deg,var(--line) 0)"><div><span><b>${pct(v)}</b><small class=mut>${l||''}</small></span></div></div>`;
const meter=(l,v)=>`<div style="margin:9px 0"><div class="row sp"><small>${l}</small><small class=mut>${pct(v)}</small></div><div class=bar><i style="width:${v*100}%;background:${col(v)}"></i></div></div>`;
const risk=r=>`<span class="pill ${cls(r)}">${lbl(r)} · ${pct(r)}</span>`;
function profTable(list,rowClick=true){return `<div class=wrap><table><thead><tr><th>Username<th>Platform<th>Followers<th>Following<th>Age (d)<th>ML<th>LLM<th>Risk<th>Status</tr></thead><tbody>${list.map(p=>`<tr class="${rowClick?'click':''}" ${rowClick?`onclick="location.hash='#/profile/${p.id}'"`:''}><td><b>@${esc(p.username)}</b><td>${p.platform}<td>${p.followers}<td>${p.following}<td>${p.age_days}<td>${pct(p.ml)}<td>${pct(p.llm)}<td>${risk(p.risk)}<td><span class="pill n">${p.status}</span></tr>`).join('')||'<tr><td colspan=9 class=mut>No profiles found.</tr>'}</tbody></table></div>`}
function makeReport(p){const id='RPT-'+String(DB.reports.length+1).padStart(4,'0');const r={id,profile:p,created:new Date().toLocaleString()};DB.reports.unshift(r);toast('Report '+id+' generated');return r}
const nav=[['dashboard','📊','Dashboard'],['analyze','🔍','Analyze Profile'],['profiles','👥','Flagged Profiles'],['batch','📦','Batch Screening'],['reports','📄','Reports'],['model','🧠','Model Insights'],['team','🏫','Project & Team'],['settings','⚙️','Settings']];
function shell(page,title,body){return `<div class=shell><aside class=side id=side><div class=logo style="padding:6px 12px 16px">🛡️ Fake<em>Profile</em> Shield</div>${nav.map(n=>`<a href="#/${n[0]}" class="${page==n[0]?'on':''}">${n[1]} ${n[2]}</a>`).join('')}<a href="#/" style="margin-top:20px">← Home page</a><a href="#/login" onclick="DB.user=null;localStorageSet('user','')">🚪 Sign out</a></aside><main class=main><div class=top><div class=row><button class="btn ghost sm burger" onclick="$('#side').classList.toggle('open')">☰</button><h2 style="margin:0">${title}</h2></div><div class=row><button class="btn ghost sm" onclick="toggleTheme()">🌓</button><span class=mut>👤 ${esc(DB.user||'Investigator')}</span></div></div>${body}</main></div>`}
function toggleTheme(){const d=document.documentElement;const n=d.dataset.theme=='dark'?'light':'dark';d.dataset.theme=n;localStorageSet('theme',n)}
