/* ================= PAGES ================= */
const pages={
'':{pub:1,html:()=>`<div class=nav><span class=logo>🛡️ Fake<em>Profile</em> Shield</span><div class=row><a href="#/model">Technology</a><a href="#/team">Team</a><button class="btn ghost sm" onclick="toggleTheme()">🌓</button><a class=btn href="#/login">Investigator Login</a></div></div>
<section class=hero><span class=tag>Major Project · B.Tech CSE (Data Science) · SVVV Indore</span><h1 style="margin-top:14px">Catch <span>fake social media profiles</span> before they cause harm</h1><p>An investigation-ready platform that blends machine-learning classification with LLM content analysis and delivers court-friendly, exportable reports.</p><div class=row style="justify-content:center"><a class=btn href="#/login">Open Dashboard</a><a class="btn ghost" href="#/analyze" onclick="if(!DB.user){DB.user='Guest Investigator'}">Try a Live Demo</a></div></section>
<section class=sec><h2>Three modules, one investigation workflow</h2><div class="grid g3">
<div class=card><div class=ico>🌲</div><h3>ML Classification</h3><p class=mut>Random Forest &amp; Gradient Boosting on follower ratios, account age, posting cadence, username entropy and engagement anomalies → fake-probability score.</p></div>
<div class=card><div class=ico>🤖</div><h3>LLM Content Analysis</h3><p class=mut>Structured prompt engineering inspects bios, captions and messages for impersonation, spam and illegal-content cues and returns a JSON verdict with rationale.</p></div>
<div class=card><div class=ico>📑</div><h3>Reporting Dashboard</h3><p class=mut>Unified risk score, evidence, filters and one-click structured case reports (PDF) for crime branches and cyber cells.</p></div></div></section>
<section class=sec><h2>How it works</h2><div class="grid g4 steps"><div class="card step"><b>Ingest</b><p class=mut>Enter a profile or upload a batch list.</p></div><div class="card step"><b>Classify</b><p class=mut>ML model scores behavioural features.</p></div><div class="card step"><b>Analyze</b><p class=mut>LLM reviews text for red flags.</p></div><div class="card step"><b>Report</b><p class=mut>Export evidence-backed case report.</p></div></div></section>
<section class=sec><h2>Built for</h2><div class="grid g4"><div class="card kpi"><b>🚓</b>Crime branches &amp; cyber cells</div><div class="card kpi"><b>🏢</b>Brand protection teams</div><div class="card kpi"><b>🛠️</b>Platform trust &amp; safety</div><div class="card kpi"><b>📈</b>Single lookups to batch screening</div></div></section>
<footer style="text-align:center;padding:30px" class=mut>© 2026 Team G-9 · Shri Vaishnav Institute of Information Technology · Guided by Prof. Kamal Borana</footer>`},
'login':{pub:1,html:()=>`<div class=login><div class="card"><div class=logo style="text-align:center;font-size:24px">🛡️ Fake<em>Profile</em> Shield</div><p class=mut style="text-align:center">Investigator sign-in</p><label>Email</label><input id=em type=email placeholder="officer@cybercell.gov.in"><label>Password</label><input id=pw type=password placeholder="••••••••"><label>Role</label><select id=role><option>Investigator<option>Supervisor<option>Admin</select><button class=btn style="width:100%;margin-top:18px" onclick="login()">Sign in</button><p class=mut style="font-size:12px">Demo mode: any credentials work until the backend auth (POST /auth/login) is connected.</p></div></div>`},
'dashboard':{html:()=>{const L=DB.profiles,h=L.filter(p=>p.risk>=.7).length,m=L.filter(p=>p.risk>=.4&&p.risk<.7).length,lo=L.length-h-m;const plats=[...new Set(L.map(p=>p.platform))];
 return shell('dashboard','Dashboard',`<div class="grid g4"><div class="card kpi"><b>${L.length}</b><span>Profiles screened</span></div><div class="card kpi"><b style="color:var(--hi)">${h}</b><span>High risk</span></div><div class="card kpi"><b style="color:var(--md)">${m}</b><span>Medium risk</span></div><div class="card kpi"><b>${DB.reports.length}</b><span>Reports generated</span></div></div>
 <div class="grid g2"><div class=card><h3>Risk distribution</h3>${meter('High',h/L.length)}${meter('Medium',m/L.length)}${meter('Low',lo/L.length)}</div>
 <div class=card><h3>By platform</h3>${plats.map(pl=>{const n=L.filter(p=>p.platform==pl);return `<div style="margin:9px 0"><div class="row sp"><small>${pl}</small><small class=mut>${n.length} profiles · ${n.filter(p=>p.risk>=.7).length} high</small></div><div class=bar><i style="width:${n.length/L.length*100}%;background:var(--pri)"></i></div></div>`}).join('')}</div></div>
 <div class=card><div class="row sp"><h3>Priority queue</h3><a href="#/profiles">View all →</a></div>${profTable([...L].sort((a,b)=>b.risk-a.risk).slice(0,6))}</div>`)}},
'analyze':{html:()=>shell('analyze','Analyze a Profile',`<div class="grid g2"><div class=card><h3>Profile details</h3><div class="grid" style="grid-template-columns:1fr 1fr;gap:0 12px"><div><label>Username</label><input id=a_u placeholder="e.g. official_sbi_help"></div><div><label>Platform</label><select id=a_pl><option>Instagram<option>Twitter/X<option>Facebook<option>LinkedIn</select></div><div><label>Followers</label><input id=a_f type=number value=50></div><div><label>Following</label><input id=a_g type=number value=1500></div><div><label>Posts</label><input id=a_po type=number value=4></div><div><label>Account age (days)</label><input id=a_ag type=number value=12></div></div><label>Bio</label><textarea id=a_b rows=2 placeholder="Paste bio text"></textarea><label>Captions / message samples</label><textarea id=a_c rows=3 placeholder="Paste captions or messages"></textarea><div class=row style="margin-top:14px"><button class=btn id=go onclick="runAnalyze()">Run analysis</button><button class="btn ghost" onclick="fillDemo()">Load suspicious sample</button></div></div><div id=res class=card><h3>Result</h3><p class=mut>Run an analysis to see the unified risk score, feature contributions and LLM verdict.</p></div></div>`)},
'profiles':{html:()=>shell('profiles','Flagged Profiles',`<div class=card><div class=row><input id=q placeholder="Search username…" style="max-width:260px" oninput="filt()"><select id=fr style="max-width:170px" onchange="filt()"><option value="">All risk levels<option value=high>High<option value=med>Medium<option value=low>Low</select><select id=fp style="max-width:170px" onchange="filt()"><option value="">All platforms<option>Instagram<option>Twitter/X<option>Facebook</select><select id=fs style="max-width:170px" onchange="filt()"><option value="">All statuses<option>Open<option>Escalated<option>Dismissed</select><button class="btn ghost sm" onclick="exportCSV()">⬇ CSV</button></div><div id=tbl style="margin-top:14px">${profTable(DB.profiles)}</div></div>`)},
'batch':{html:()=>shell('batch','Batch Screening',`<div class=card><p class=mut>Paste one username per line or upload a .txt/.csv list. Results appear below and can be added to the queue.</p><textarea id=bl rows=6 placeholder="user_one&#10;user_two&#10;user_three"></textarea><div class=row style="margin-top:12px"><input type=file id=bf accept=".txt,.csv" style="max-width:280px" onchange="loadFile(this)"><button class=btn onclick="runBatch()">Screen accounts</button></div><div id=bp></div></div><div id=br></div>`)},
'reports':{html:()=>shell('reports','Investigation Reports',`<div class=card>${DB.reports.length?`<div class=wrap><table><thead><tr><th>ID<th>Profile<th>Risk<th>Created<th></tr></thead><tbody>${DB.reports.map(r=>`<tr><td><b>${r.id}</b><td>@${esc(r.profile.username)}<td>${risk(r.profile.risk)}<td>${r.created}<td><a class="btn sm" href="#/report/${r.id}">Open</a></tr>`).join('')}</tbody></table></div>`:'<p class=mut>No reports yet. Open any profile and click <b>Generate report</b>.</p>'}</div>`)},
'model':{html:()=>{const M=[['Random Forest',.951,.943,.958,.950,.982],['Gradient Boosting',.962,.957,.966,.961,.989]],imp=[['Follower/following ratio',.27],['Account age',.21],['Posting frequency',.16],['Username entropy',.14],['Engagement rate',.12],['Bio length / keywords',.10]];
 return shell('model','Model Insights',`<div class=card style="border-left:4px solid var(--md)">⚠️ Values below are <b>illustrative placeholders</b>. Replace via <code>GET /metrics</code> once the classifier is trained on the Kaggle dataset.</div>
 <div class=card><h3>Model comparison</h3><div class=wrap><table><thead><tr><th>Model<th>Accuracy<th>Precision<th>Recall<th>F1<th>ROC-AUC</tr></thead><tbody>${M.map(r=>`<tr><td><b>${r[0]}</b>${r.slice(1).map(v=>`<td>${(v*100).toFixed(1)}%`).join('')}</tr>`).join('')}</tbody></table></div></div>
 <div class="grid g2"><div class=card><h3>Feature importance</h3>${imp.map(i=>meter(i[0],i[1]*3)).join('')}</div>
 <div class=card><h3>ROC curve</h3><svg viewBox="0 0 220 220" style="width:100%;max-width:300px;display:block;margin:auto"><rect x=20 y=10 width=190 height=190 fill="none" stroke="var(--line)"/><line x1=20 y1=200 x2=210 y2=10 stroke="var(--mut)" stroke-dasharray="4"/><path d="M20 200 C22 80 40 30 100 20 S190 12 210 10" fill="none" stroke="var(--pri)" stroke-width=3 /><path d="M20 200 C24 90 50 40 110 26 S195 14 210 10" fill="none" stroke="var(--pri2)" stroke-width=3 /><text x=110 y=216 font-size=10 fill="var(--mut)" text-anchor=middle>False positive rate</text></svg><p class=mut style="text-align:center"><span style="color:var(--pri)">■</span> Gradient Boosting <span style="color:var(--pri2)">■</span> Random Forest</p></div></div>
 <div class=card><h3>Confusion matrix (Gradient Boosting)</h3><div class="grid" style="grid-template-columns:repeat(2,120px);gap:6px"><div class=card style="background:var(--lo);color:#fff;text-align:center;margin:0">TN<br><b>912</b></div><div class=card style="background:var(--md);color:#fff;text-align:center;margin:0">FP<br><b>38</b></div><div class=card style="background:var(--md);color:#fff;text-align:center;margin:0">FN<br><b>33</b></div><div class=card style="background:var(--lo);color:#fff;text-align:center;margin:0">TP<br><b>917</b></div></div></div>`)}},
'team':{html:()=>shell('team','Project & Team',`<div class=card><h3>Fake Social Media Profile Detection and Reporting System</h3><p class=mut>Team ID G-9 · Guide: Prof. Kamal Borana · Dept. of CSE, Shri Vaishnav Institute of Information Technology, SVVV Indore · Jul–Dec 2026</p></div>
 <div class="grid g4">${[['Paridhi Agrawal','23100BTCSDSI14379','Backend'],['Prakrati Dubey','23100BTCSDSI14381','Frontend'],['Pratha Singh Naruka','23100BTCSDSI14383','Team member'],['Priyanshu Salunkhe','23100BTCSDSI14386','Team member']].map(t=>`<div class=card style="text-align:center"><div class=ico>🎓</div><b>${t[0]}</b><br><small class=mut>${t[1]}</small><br><span class=tag>${t[2]}</span></div>`).join('')}</div>
 <div class="grid g2"><div class=card><h3>Status – Sprint 1 of 6</h3><p>Requirements &amp; Design (Weeks 1–2) · <span class="pill low">On track</span></p>${meter('Sprint 1 progress',.5)}<p class=mut>Jira board and Git repo set up; Use Case Diagram is next. CI/CD (GitHub Actions) planned for Week 9.</p></div>
 <div class=card><h3>Tech stack</h3>${['Python','Flask / FastAPI','scikit-learn','pandas / NumPy','LLM API','PostgreSQL / MySQL','GitHub Actions','Google Cloud Platform','Jira'].map(t=>`<span class=tag>${t}</span>`).join('')}</div></div>
 <div class=card><h3>Objectives</h3><ul><li>Detect fake / impersonating profiles with high accuracy<li>Analyze content for impersonation, spam or illegal indicators via LLM<li>Generate structured, exportable investigation reports<li>Provide an investigator dashboard to review, filter and act on flagged profiles</ul></div>`)},
'settings':{html:()=>shell('settings','Settings',`<div class="grid g2"><div class=card><h3>Backend connection</h3><label>API base URL</label><input id=api value="${esc(CFG.API_BASE)}"><label>Mode</label><select id=mode><option value=1 ${CFG.USE_MOCK?'selected':''}>Mock data (demo)<option value=0 ${CFG.USE_MOCK?'':'selected'}>Live backend</select><button class=btn style="margin-top:14px" onclick="saveCfg()">Save</button></div>
 <div class=card><h3>Risk thresholds</h3><label>High risk ≥ <b id=t1v>70</b>%</label><input type=range min=50 max=95 value=70 oninput="t1v.textContent=this.value"><label>Medium risk ≥ <b id=t2v>40</b>%</label><input type=range min=10 max=60 value=40 oninput="t2v.textContent=this.value"><label>Fusion weight – ML model: <b id=t3v>60</b>%</label><input type=range min=0 max=100 value=60 oninput="t3v.textContent=this.value"><p class=mut style="font-size:12px">Demo controls. Wire to backend config when available.</p></div></div>`)}
};
